// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int countHigh = 0, countLow = 0, i = 0;
		while (i < n) {
			if (Math.random() > 0.5) {
				countHigh++;
			} else {
				countLow++;
			}
			i++;
		}
		System.out.println("> 0.5: " + countHigh + " times");
		System.out.println("<= 0.5: " + countLow + " times");
		if (countHigh == 0 || countLow == 0) {
			System.out.println();
		} else {
			System.out.println((double) Math.min(countHigh, countLow) / Math.max(countLow, countHigh));
		}
	}
}
